### ISSUE TITLE
Compile error when make TARGET="F072" 

### ISSUE THREAD

**Issue by ohmytime** [erikkaashoek/NanoVNA#113]
My device is tinySA ,HW version V0.3.1_EL ,so I select this command . 
Then came across this error, please check.

Source : git version  465f120

<img width="958" alt="image" src="https://github.com/user-attachments/assets/390cbb63-4bfe-452e-a303-e6208f19b2f1">

**Comment by MrBluehub** [comment]
Has the issue been resolved? 

I recieve the same errors when compiling with  TARGET="F303" for my TinySA Ultra HW Version 0.4.5.1.1

**Edit: Resolved.** I accidentally typed target="F303" instead of TARGET="F303". After deleting the TinySA folder & cloning again the compilation got done without errors.

**Comment by ohmytime** [comment]
Thank you, now resolved.

**Comment by Markus99-stac** [comment]
Good day. Please help me. When entering the make target="F303" command, it returns the following error.

![Image](https://github.com/user-attachments/assets/84a4977e-8c89-4443-b5a2-fd31b92c7b63)
![Image](https://github.com/user-attachments/assets/baa570a2-d1e8-41b8-b759-91e23dd15d2a)
![Image](https://github.com/user-attachments/assets/15e25ffc-b896-4fb9-ad55-b9892051ee3a)
![Image](https://github.com/user-attachments/assets/3d67d26c-f1a6-42c5-bd01-17dbe5882c60)
